[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "moatt_types"
dynamic = [ "version" ]

[tool.setuptools.dynamic.version]
attr = "moatt_types.VERSION"
