"""Initial migration.

Revision ID: 66cb7cb6f59c
Revises: 
Create Date: 2023-02-15 20:27:12.790717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cb7cb6f59c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('value', sa.String(length=36), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('last_access', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('value')
    )
    op.create_table('probes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('mac', sa.Text(), nullable=True),
    sa.Column('token', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['token'], ['tokens.value'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('probes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_probes_mac'), ['mac'], unique=True)

    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Integer(), nullable=True),
    sa.Column('session_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['token'], ['tokens.value'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('sims',
    sa.Column('iccid', sa.String(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('iccid')
    )
    op.create_table('apdu_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('iccid', sa.String(), nullable=True),
    sa.Column('command', sa.Enum('Apdu', 'Reset', name='apduop'), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['iccid'], ['sims.iccid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imsis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imsi', sa.String(), nullable=False),
    sa.Column('registered', sa.DateTime(), nullable=False),
    sa.Column('sim_iccid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sim_iccid'], ['sims.iccid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imsis')
    op.drop_table('apdu_log')
    op.drop_table('sims')
    op.drop_table('providers')
    with op.batch_alter_table('probes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_probes_mac'))

    op.drop_table('probes')
    op.drop_table('tokens')
    # ### end Alembic commands ###
