"""Wireguard Features

Revision ID: 6b3ed4b5a801
Revises: 
Create Date: 2021-03-23 13:14:56.428919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3ed4b5a801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wireguard_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.Text(), nullable=True),
    sa.Column('publickey', sa.Text(), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('allow_registration', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_wireguard_config_mac'), 'wireguard_config', ['mac'], unique=True)
    op.create_index(op.f('ix_wireguard_config_publickey'), 'wireguard_config', ['publickey'], unique=False)

    op.create_table('wireguard_config_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.Text(), nullable=True),
    sa.Column('publickey', sa.Text(), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wireguard_config_attempt')
    op.drop_index(op.f('ix_wireguard_config_publickey'), table_name='wireguard_config')
    op.drop_index(op.f('ix_wireguard_config_mac'), table_name='wireguard_config')
    op.drop_table('wireguard_config')
    # ### end Alembic commands ###
