"""ProbeSystemInformation features

Revision ID: 8a77c2747150
Revises: 759ad3bcc0d3
Create Date: 2021-04-29 12:46:44.269438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a77c2747150'
down_revision = '759ad3bcc0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probe_system_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('probe_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('information', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['probe_id'], ['probe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('probe_system_information')
    # ### end Alembic commands ###
