"""Basic Probe + Probe Reboot Log

Revision ID: 9cea40c99d9b
Revises: 6b3ed4b5a801
Create Date: 2021-04-26 13:25:50.743412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cea40c99d9b'
down_revision = '6b3ed4b5a801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probe',
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_candidate', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('token_last_access', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('mac', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_probe_mac'), 'probe', ['mac'], unique=True)
    op.create_index(op.f('ix_probe_token'), 'probe', ['token'], unique=True)
    op.create_index(op.f('ix_probe_token_candidate'), 'probe', ['token_candidate'], unique=True)
    op.create_table('probe_reboot_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('probe_reboot_log')
    op.drop_index(op.f('ix_probe_token_candidate'), table_name='probe')
    op.drop_index(op.f('ix_probe_token'), table_name='probe')
    op.drop_index(op.f('ix_probe_mac'), table_name='probe')
    op.drop_table('probe')
    # ### end Alembic commands ###
